#!/bin/sh

DAEMON=/sbin/iptables
NAME=firewall
DESC="iptables based firewall"

test -x $DAEMON || exit 0

if [ `whoami` != "root" ]; then
  echo "$0: Permission non accordée"
  exit 1;
fi 

iptables -F
iptables -F -t mangle
iptables -F -t nat
iptables -X
iptables -X -t mangle
iptables -X -t nat
echo - Clear : [OK]

iptables -P INPUT DROP
echo - Drop INPUT connections : [OK]

iptables -P OUTPUT ACCEPT
echo - Allow OUTPUT connections : [OK]

iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
echo - Do not break existing connections : [OK]

# Autoriser loopback
iptables -A INPUT -i lo -j ACCEPT
echo - Allow loopback : [OK]

# ICMP (Ping)
iptables -A INPUT -p icmp -j ACCEPT
echo - Allow ping : [OK]

# SSH
iptables -A INPUT -p tcp --dport 22 -j ACCEPT
iptables -A INPUT -p tcp --dport 2222 -j ACCEPT
echo - Allow SSH : [OK]

exit 0
